GAS_REWARD = 0.1

WIGGLE_PENALTY = 0.05
WIGGLE_TOLERANCE = 0.15

OFF_ROAD_WHEEL_PENALTY = 0.2
MAX_OFF_ROAD_STEPS = 10

MAX_LINE_DISTANCE_REWARD = 1.3
LINE_DISTANCE_REWARD_DROPOFF = 7.0
LINE_TARGET_SPEED_REWARD_FACTOR = 1.0
TARGET_SPEED = 100.0

MAX_ANGLE_DIFF_REWARD = 0.5
ANGLE_DIFF_REWARD_DROPOFF = 1.0